#!/bin/bash
set -e

if [[ $# == 0 ]];then
    echo "Usage : $0 video_path"
    exit
fi

if [ ! -f $1 ];then
    echo "!!!Error : file $1 not exist!"
    exit
fi

videoPath=$1

line1=`ffmpeg -i $videoPath -vcodec copy -f rawvideo -y /dev/null 2>&1 | tr ^M '\n' | awk '/Duration/'`
line2=`ffmpeg -i $videoPath -vcodec copy -f rawvideo -y /dev/null 2>&1 | tr ^M '\n' | awk '/Stream/' | head -n 1`
line3=`ffmpeg -i $videoPath -vcodec copy -f rawvideo -y /dev/null 2>&1 | tr ^M '\n' | awk '/^frame=/'`

duration=`echo $line1 | awk -F, '{print $1}' | awk '{print $2}'`
bitrate=`echo $line1 | awk -F, '{print  $3}' | awk -F: '{print $2}'`
codec=`echo $line2 | awk -FV '{print $2}' | awk -F, '{print $1}' |awk -F: '{print $2}'`
format=`echo $line2 | awk -FV '{print $2}' | awk -F, '{print $2}'`
resolution=`echo $line2 | awk -FV '{print $2}' | awk -F, '{print $3}'`
fps=`echo $line2 | awk -FV '{print $2}' | awk -F, '{print $4}'`
count=`echo $line3 | awk -F= '{print $2}' | awk '{print $1}'`

echo "Duration : $duration"
echo "Bitrate : $bitrate"
echo "Codec : $codec"
echo "Data Format : $format"
echo "Resolution : $resolution"
echo "Frame Rate : $fps"
echo "Total Frame Count : $count"
